name: mobile_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  axios: ^0.0.1
  bubble_tab_indicator: ^0.1.6
  cloud_firestore: ^3.1.4
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  custom_navigator: ^0.3.0
  date_picker_timeline: ^1.2.3
  date_time_picker: ^2.1.0
  dio: ^4.0.4
  dropdown_search: ^2.0.1
  dropdownfield: ^1.0.3
  duration_picker: ^1.1.0+1
  file_picker: ^4.2.8
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  firebase_storage: ^10.2.3
  fl_chart: ^0.41.0
  flutter:
    sdk: flutter
  flutter_beautiful_popup: ^1.7.0
  flutter_colorpicker: ^1.0.3
  flutter_form_builder: ^7.0.0
  flutter_highlight: ^0.7.0
  flutter_hooks: ^0.18.1
  flutter_svg: ^1.0.0
  font_awesome_flutter: ^9.2.0
  geolocator: ^8.0.3
  geolocator_android: any
  geolocator_platform_interface: any
  google_maps_flutter: ^2.0.4
  flutter_localizations:
    sdk: flutter
  google_maps_flutter_web: ^0.3.2
  http: ^0.13.4
  iconly: ^1.0.1
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  jiffy: ^5.0.0
  json_serializable: ^4.1.4
  location: ^4.3.0
  location_web: ^3.1.1
  percent_indicator: ^4.0.0
  persistent_bottom_nav_bar: ^4.0.2
  place_picker: ^0.9.20-nullsafety
  provider: ^5.0.0
  recase: ^4.0.0
  rflutter_alert: ^2.0.4
  searchable_dropdown: ^1.1.3
  sliding_sheet: ^0.5.2
  stop_watch_timer: ^1.3.1
  url_launcher: ^6.0.17
  geolocator_apple: any
  flutter_polyline_points: ^1.0.0
dev_dependencies:
  build_runner: ^1.12.2
  flutter_forms: ^1.0.0
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter
  integration_test:           
    sdk: flutter              
  test: ^1.14.4   

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/map/
    - assets/locations.json
  fonts:
    - family: PencilCirceled
      fonts:
        - asset: assets/fonts/PencilCirceled.ttf
    - family: CancelCircled
      fonts:
        - asset: assets/fonts/CancelCircled.ttf
    - family: MinusCircled
      fonts:
        - asset: assets/fonts/MinusCircled.ttf
    - family: Info
      fonts:
        - asset: assets/fonts/Info.ttf
    - family: Plus
      fonts:
        - asset: assets/fonts/Plus.ttf
    - family: DatePicker
      fonts:
        - asset: assets/fonts/DatePicker.ttf
    - family: PlusSlim
      fonts:
        - asset: assets/fonts/PlusSlim.ttf
    - family: PlusSlim2
      fonts:
        - asset: assets/fonts/PlusSlim2.ttf
    - family: Dot
      fonts:
        - asset: assets/fonts/Dot.ttf
    - family: CheckCircle
      fonts:
        - asset: assets/fonts/CheckCircle.ttf
    - family: More
      fonts:
        - asset: assets/fonts/More.ttf
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true
module:
    androidX: true 
