/// Flutter icons Info
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Info
///      fonts:
///       - asset: fonts/Info.ttf
///
///
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
///
import 'package:flutter/widgets.dart';

class Info {
  Info._();

  static const _kFontFam = 'Info';
  static const String? _kFontPkg = null;

  static const IconData info =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
