/// Flutter icons PlusSlim2
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PlusSlim2
///      fonts:
///       - asset: fonts/PlusSlim2.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class PlusSlim2 {
  PlusSlim2._();

  static const _kFontFam = 'PlusSlim2';
  static const String? _kFontPkg = null;

  static const IconData plus_circled =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
