// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfT95_ylp95OaOKtMSjSzPbHoTGScG52g',
    appId: '1:274087100770:web:a42bf46498463317582c3b',
    messagingSenderId: '274087100770',
    projectId: 'fluttermap01-335114',
    authDomain: 'fluttermap01-335114.firebaseapp.com',
    storageBucket: 'fluttermap01-335114.appspot.com',
    measurementId: 'G-CFQSGL3SNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDteR-CFSJC_0pqsL2bDeLENHReeJtiIws',
    appId: '1:274087100770:android:1e042152171c4c61582c3b',
    messagingSenderId: '274087100770',
    projectId: 'fluttermap01-335114',
    storageBucket: 'fluttermap01-335114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAthQQ4ofd4wjByDv3w6yHSt7mRJ5rZHNY',
    appId: '1:274087100770:ios:78673a61433b172b582c3b',
    messagingSenderId: '274087100770',
    projectId: 'fluttermap01-335114',
    storageBucket: 'fluttermap01-335114.appspot.com',
    iosClientId: '274087100770-df5urm4imtusn737oe4r8d8mv88ajjbs.apps.googleusercontent.com',
    iosBundleId: 'com.exemple.app',
  );
}
