# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'

end
